name = "e-spamchecker"
main = "dist/worker.js"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"

[[kv_namespaces]]
binding = "kv"
id = "6dbd9237cb2e4766879bd072551584ef"

[vars]
UUID = "21bb0aad-c868-40a8-a896-5a9afdb05c5c"
TR_PASS = "EfN!9o*{Ov[uO4P;"
SUB_PATH = "RcHPaAc1YerUhXcS"

