name = "e-spamchecker"
main = "dist/worker.js"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"

[[kv_namespaces]]
binding = "kv"
id = "6dbd9237cb2e4766879bd072551584ef"

